[package]
name = "popsicle"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["scuttlebutt/nightly", "ocelot/nightly", "ocelot/nightly"]
psty = ["fancy-garbling", "openssl"]
psty_payload = ["fancy-garbling", "serde", "serde_json", "fancy-garbling/serde1"]

[dependencies]
ocelot         = { path = "../ocelot" }
scuttlebutt    = { path = "../scuttlebutt" }
itertools      = "0.10.0"
rand           = "0.7"
sha2           = "0.9.3"
fancy-garbling = { path = "../fancy-garbling", optional = true }
openssl        = { version = "0.10.32", optional = true }
serde          = {version = "1.0.117", features = ["derive"], optional = true }
serde_json     = {version = "1.0.59", optional = true }

[dev-dependencies]
criterion  = "0.3.4"

[[bench]]
name = "psz"
harness = false

[[bench]]
name = "psty"
harness = false
required-features = ["psty"]

[[bench]]
name = "psty_payload"
harness = false
required-features = ["psty_payload"]

[[example]]
name = "psty"
required-features = ["psty"]

[[example]]
name = "psty-payload"
required-features = ["psty"]
